### ISSUE TITLE
UseLazyLoadingProxies conflict

### ISSUE THREAD

**Issue by carloscds** [ralmsdeveloper/Ralms.EntityFrameworkCore.Extensions#1]
When I install extension I have this conflict:
![image](https://user-images.githubusercontent.com/1697221/41228382-93bb40ac-6d4e-11e8-9415-0c2325f9506e.png)

**Comment by ralmsdeveloper** [comment]
it is necessary to remove **Microsoft.EntityFrameworkCore.Proxies**, all work will be done by the Extension which contains the same functions as Microsoft.EntityFrameworkCore.Proxies, a workaround this needs to be done to clear the injected proxy in the class, what we have is just not mandatory to put navigation as virtual in some scenarios.
