### ISSUE TITLE
Not supported error

### ISSUE THREAD

**Issue by carloscds** [ralmsdeveloper/Ralms.EntityFrameworkCore.Extensions#2]
![image](https://user-images.githubusercontent.com/1697221/41228420-b7f93dd4-6d4e-11e8-9c62-8360115636cc.png)

**Comment by ralmsdeveloper** [comment]
This is an **IQueryable** method, and is only used for one annotation.

You need to execute a projection, so we need to call.

For Sample:
* ToList()
* FirstOrDefault()
* Single()

Thanks!

**Comment by carloscds** [comment]
@ralmsdeveloper Project can leave application slow.

**Comment by ralmsdeveloper** [comment]
@carloscds 
Have you enabled **RalmsExtendFunctions()** in **OnConfiguring**?

This error occurs when the extension is not enabled, so internally the extension did not resolve the methods.

```csharp
protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
{
    optionsBuilder
        .UseSqlServer("Server=(localdb)\\mssqllocaldb;Database=TesteExtensao;Integrated Security=True;")
        .RalmsExtendFunctions();
}
```

**Comment by ralmsdeveloper** [comment]
Is this why I have not done the documentation yet?!
My apologies, I'll put this in the documentation.

**Comment by carloscds** [comment]
@ralmsdeveloper No problem!
