### ISSUE TITLE
sql statement generated when using sql 2008

### ISSUE THREAD

**Issue by 284247028** [ralmsdeveloper/Ralms.EntityFrameworkCore.Extensions#3]
There is a problem with the sql statement generated when using sql 2008

FROM [xxxx] AS [c] WITH (NOLOCK) 
OFFSET @__p_0 ROWS FETCH NEXT @__p_1 ROWS ONLY',N'@__p_0 int,@__p_1 int'

"OFFSET, FETCH" syntax does not exist in sql 2008
If i don't use RalmsExtendFunctions, the generated sql statement is normal.

Ef configuration is as follows:
  services.AddDbContext<xxxx>(options =>
            options.UseSqlServer(connectionString, b => b.UseRowNumberForPaging()).RalmsExtendFunctions())
            .AddUnitOfWork<xxxx>();

**Comment by ralmsdeveloper** [comment]
Thank you very much for contacting us, please upgrade to 1.0.4, it has been fixed.

Now we have a correct output for SQL 2008.

```sql
SELECT [t0].[Id], [t0].[Date], [t0].[Name]
FROM (
    SELECT [p].[Id], [p].[Date], [p].[Name], ROW_NUMBER() OVER(ORDER BY [p].[Id]) AS [__RowNumber__]
    FROM [Blogs] AS [p] WITH (NOLOCK) 
) AS [t0]
WHERE ([t0].[__RowNumber__] > 5) AND ([t0].[__RowNumber__] <= 15)
```

**Comment by 284247028** [comment]
thank you!
